server:
  port: 8080
  servlet:
    context-path: /auth-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    auth-service:
      jdbc-url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: root
