server:
  port: 8080
  servlet:
    context-path: /auth-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    auth-service:
      jdbc-url: jdbc:mysql://localhost:3306/moments?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: dpc
      password: dpc123
  mail:
    host: smtp.qq.com
    port: 465
    username: 1085529137@qq.com
    password: fbjdznbsjftbjaci
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: dbfaed2e681d18e8c4e4
            clientSecret: c3df86f2b0d538dfc5260e5368647ae3e352c015
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://192.160.0.71:8080/auth-service/oauth2/callback/github
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

#facebook:
#  client:
#    clientId: 233668646673605
#    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me
#github:
#  client:
#    clientId: bd1c0a783ccdd1c9b9e4
#    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userAuthorizationUri: https://github.com/login/oauth/authorize
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://api.github.com/user
